module.exports = [{
  "name": "23andme",
  "github": "https://github.com/SocialiteProviders/23andme",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/23andme",
  "listener": "SocialiteProviders\\TwentyThreeAndMe\\TwentyThreeAndMeExtendSocialite@handle"
}, {
  "name": "37Signals",
  "github": "https://github.com/SocialiteProviders/37Signals",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/37signals",
  "listener": "SocialiteProviders\\ThirtySevenSignals\\ThirtySevenSignalsExtendSocialite@handle"
}, {
  "name": "500px",
  "github": "https://github.com/SocialiteProviders/500px",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/500px",
  "listener": "SocialiteProviders\\FiveHundredPixel\\FiveHundredPixelExtendSocialite@handle"
}, {
  "name": "AngelList",
  "github": "https://github.com/SocialiteProviders/AngelList",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/angellist",
  "listener": "SocialiteProviders\\AngelList\\AngelListExtendSocialite@handle"
}, {
  "name": "App.net",
  "github": "https://github.com/SocialiteProviders/AppNet",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/appnet",
  "listener": "SocialiteProviders\\AppNet\\AppNetExtendSocialite@handle"
}, {
  "name": "Asana",
  "github": "https://github.com/SocialiteProviders/Asana",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/asana",
  "listener": "SocialiteProviders\\Asana\\AsanaExtendSocialite@handle"
}, {
  "name": "Bit.ly",
  "github": "https://github.com/SocialiteProviders/Bit.ly",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/bitly",
  "listener": "SocialiteProviders\\Bitly\\BitlyExtendSocialite@handle"
}, {
  "name": "Box",
  "github": "https://github.com/SocialiteProviders/Box",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/box",
  "listener": "SocialiteProviders\\Box\\BoxExtendSocialite@handle"
}, {
  "name": "Buffer",
  "github": "https://github.com/SocialiteProviders/Buffer",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/buffer",
  "listener": "SocialiteProviders\\Buffer\\BufferExtendSocialite@handle"
}, {
  "name": "CampaignMonitor",
  "github": "https://github.com/SocialiteProviders/CampaignMonitor",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/campaignmonitor",
  "listener": "SocialiteProviders\\CampaignMonitor\\CampaignMonitorExtendSocialite@handle"
}, {
  "name": "Cheddar",
  "github": "https://github.com/SocialiteProviders/Cheddar",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/cheddar",
  "listener": "SocialiteProviders\\Cheddar\\CheddarExtendSocialite@handle"
}, {
  "name": "Coinbase",
  "github": "https://github.com/SocialiteProviders/Coinbase",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/coinbase",
  "listener": "SocialiteProviders\\Coinbase\\CoinbaseExtendSocialite@handle"
}, {
  "name": "ConstantContact",
  "github": "https://github.com/SocialiteProviders/ConstantContact",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/constantcontact",
  "listener": "SocialiteProviders\\ConstantContact\\ConstantContactExtendSocialite@handle"
}, {
  "name": "Coursera",
  "github": "https://github.com/SocialiteProviders/Coursera",
  "maintainer": "davetosh",
  "maintainer_profile": "https://github.com/davetosh",
  "packagist": "socialiteproviders/coursera",
  "listener": "SocialiteProviders\\Coursera\\CourseraExtendSocialite@handle"
}, {
  "name": "Dailymile",
  "github": "https://github.com/SocialiteProviders/Dailymile",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/dailymile",
  "listener": "SocialiteProviders\\Dailymile\\DailymileExtendSocialite@handle"
}, {
  "name": "Dailymotion",
  "github": "https://github.com/SocialiteProviders/Dailymotion",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/dailymotion",
  "listener": "SocialiteProviders\\Dailymotion\\DailymotionExtendSocialite@handle"
}, {
  "name": "Deezer",
  "github": "https://github.com/SocialiteProviders/Deezer",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/deezer",
  "listener": "SocialiteProviders\\Deezer\\DeezerExtendSocialite@handle"
}, {
  "name": "deviantART",
  "github": "https://github.com/SocialiteProviders/deviantART",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/deviantart",
  "listener": "SocialiteProviders\\DeviantArt\\DeviantartExtendSocialite@handle"
}, {
  "name": "DigitalOcean",
  "github": "https://github.com/SocialiteProviders/DigitalOcean",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/digitalocean",
  "listener": "SocialiteProviders\\DigitalOcean\\DigitalOceanExtendSocialite@handle"
}, {
  "name": "Discord",
  "github": "https://github.com/SocialiteProviders/Discord",
  "maintainer": "eklundchristopher",
  "maintainer_profile": "https://github.com/eklundchristopher",
  "packagist": "socialiteproviders/discord",
  "listener": "SocialiteProviders\\Discord\\DiscordExtendSocialite@handle"
}, {
  "name": "Disqus",
  "github": "https://github.com/SocialiteProviders/Disqus",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/disqus",
  "listener": "SocialiteProviders\\Disqus\\DisqusExtendSocialite@handle"
}, {
  "name": "Douban",
  "github": "https://github.com/SocialiteProviders/Douban",
  "maintainer": "xyxu",
  "maintainer_profile": "https://github.com/xyxu",
  "packagist": "socialiteproviders/douban",
  "listener": "SocialiteProviders\\Douban\\DoubanExtendSocialite@handle"
}, {
  "name": "Dribbble",
  "github": "https://github.com/SocialiteProviders/Dribbble",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/dribbble",
  "listener": "SocialiteProviders\\Dribbble\\DribbbleExtendSocialite@handle"
}, {
  "name": "Dropbox",
  "github": "https://github.com/SocialiteProviders/Dropbox",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/dropbox",
  "listener": "SocialiteProviders\\Dropbox\\DropboxExtendSocialite@handle"
}, {
  "name": "Envato",
  "github": "https://github.com/SocialiteProviders/Envato",
  "maintainer": "dennisoderwald",
  "maintainer_profile": "https://github.com/dennisoderwald",
  "packagist": "socialiteproviders/envato",
  "listener": "SocialiteProviders\\Envato\\EnvatoExtendSocialite@handle"
}, {
  "name": "Etsy",
  "github": "https://github.com/SocialiteProviders/Etsy",
  "maintainer": "felipemarques",
  "maintainer_profile": "https://github.com/felipemarques",
  "packagist": "socialiteproviders/Etsy",
  "listener": "SocialiteProviders\\Etsy\\EtsyExtendSocialite@handle"
}, {
  "name": "Eventbrite",
  "github": "https://github.com/SocialiteProviders/Eventbrite",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/eventbrite",
  "listener": "SocialiteProviders\\Eventbrite\\EventbriteExtendSocialite@handle"
}, {
  "name": "Everyplay",
  "github": "https://github.com/SocialiteProviders/Everyplay",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/everyplay",
  "listener": "SocialiteProviders\\Everyplay\\EveryplayExtendSocialite@handle"
}, {
  "name": "EyeEm",
  "github": "https://github.com/SocialiteProviders/EyeEm",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/eyeem",
  "listener": "SocialiteProviders\\EyeEm\\EyeEmExtendSocialite@handle"
}, {
  "name": "Fitbit",
  "github": "https://github.com/SocialiteProviders/Fitbit",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/fitbit",
  "listener": "SocialiteProviders\\Fitbit\\FitbitExtendSocialite@handle"
}, {
  "name": "Flickr",
  "github": "https://github.com/SocialiteProviders/Flickr",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/flickr",
  "listener": "SocialiteProviders\\Flickr\\FlickrExtendSocialite@handle"
}, {
  "name": "Foursquare",
  "github": "https://github.com/SocialiteProviders/Foursquare",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/foursquare",
  "listener": "SocialiteProviders\\Foursquare\\FoursquareExtendSocialite@handle"
}, {
  "name": "GitLab",
  "github": "https://github.com/SocialiteProviders/GitLab",
  "maintainer": "mrtnsn",
  "maintainer_profile": "https://github.com/mrtnsn",
  "packagist": "socialiteproviders/gitlab",
  "listener": "SocialiteProviders\\GitLab\\GitLabExtendSocialite@handle"
}, {
  "name": "Goodreads",
  "github": "https://github.com/SocialiteProviders/Goodreads",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/goodreads",
  "listener": "SocialiteProviders\\Goodreads\\GoodreadsExtendSocialite@handle"
}, {
  "name": "Google+",
  "github": "https://github.com/SocialiteProviders/Google-Plus",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/google",
  "listener": "SocialiteProviders\\Google\\GoogleExtendSocialite@handle",
  "socialite_name": "google"
}, {
  "name": "Harvest",
  "github": "https://github.com/SocialiteProviders/Harvest",
  "maintainer": "jjozwiak",
  "maintainer_profile": "https://github.com/jjozwiak",
  "packagist": "socialiteproviders/harvest",
  "listener": "SocialiteProviders\\Harvest\\HarvestExtendSocialite@handle"
}, {
  "name": "Heroku",
  "github": "https://github.com/SocialiteProviders/Heroku",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/heroku",
  "listener": "SocialiteProviders\\Heroku\\HerokuExtendSocialite@handle"
}, {
  "name": "Hitbox",
  "github": "https://github.com/SocialiteProviders/Hitbox",
  "maintainer": "Meroje",
  "maintainer_profile": "https://github.com/Meroje",
  "packagist": "socialiteproviders/hitbox",
  "listener": "SocialiteProviders\\Hitbox\\HitboxExtendSocialite@handle"
}, {
  "name": "Human API",
  "github": "https://github.com/SocialiteProviders/Human-API",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/humanapi",
  "listener": "SocialiteProviders\\HumanApi\\HumanApiExtendSocialite@handle"
}, {
  "name": "Imgur",
  "github": "https://github.com/SocialiteProviders/Imgur",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/imgur",
  "listener": "SocialiteProviders\\Imgur\\ImgurExtendSocialite@handle"
}, {
  "name": "Instagram",
  "github": "https://github.com/SocialiteProviders/Instagram",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/instagram",
  "listener": "SocialiteProviders\\Instagram\\InstagramExtendSocialite@handle"
}, {
  "name": "Jawbone",
  "github": "https://github.com/SocialiteProviders/Jawbone",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/jawbone",
  "listener": "SocialiteProviders\\Jawbone\\JawboneExtendSocialite@handle"
}, {
  "name": "Jira",
  "github": "https://github.com/SocialiteProviders/Jira",
  "maintainer": "xdzeta",
  "maintainer_profile": "https://github.com/xdzeta",
  "packagist": "socialiteproviders/jira",
  "listener": "SocialiteProviders\\Jira\\JiraExtendSocialite@handle"
}, {
  "name": "Kakao",
  "github": "https://github.com/SocialiteProviders/Kakao",
  "maintainer": "visualplus",
  "maintainer_profile": "https://github.com/visualplus",
  "packagist": "socialiteproviders/kakao",
  "listener": "SocialiteProviders\\Kakao\\KakaoExtendSocialite@handle"
}, {
  "name": "LINE",
  "github": "https://github.com/SocialiteProviders/Line",
  "maintainer": "mix5003",
  "maintainer_profile": "https://github.com/mix5003",
  "packagist": "socialiteproviders/line",
  "listener": "SocialiteProviders\\Line\\LineExtendSocialite@handle"
}, {
  "name": "LinkedIn",
  "github": "https://github.com/SocialiteProviders/LinkedIn",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/linkedin",
  "listener": "SocialiteProviders\\LinkedIn\\LinkedInExtendSocialite@handle"
}, {
  "name": "MailChimp",
  "github": "https://github.com/SocialiteProviders/MailChimp",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/mailchimp",
  "listener": "SocialiteProviders\\MailChimp\\MailChimpExtendSocialite@handle"
}, {
  "name": "Medium",
  "github": "https://github.com/SocialiteProviders/Medium",
  "maintainer": "barooney",
  "maintainer_profile": "https://github.com/barooney",
  "packagist": "socialiteproviders/Medium",
  "listener": "SocialiteProviders\\Medium\\MediumExtendSocialite@handle"
}, {
  "name": "Meetup",
  "github": "https://github.com/SocialiteProviders/Meetup",
  "maintainer": "AndyWendt",
  "maintainer_profile": "https://github.com/AndyWendt",
  "packagist": "socialiteproviders/meetup",
  "listener": "SocialiteProviders\\Meetup\\MeetupExtendSocialite@handle"
}, {
  "name": "Microsoft Azure",
  "github": "https://github.com/SocialiteProviders/Microsoft-Azure",
  "maintainer": "chrishemmings",
  "maintainer_profile": "https://github.com/chrishemmings",
  "packagist": "socialiteproviders/microsoft-azure",
  "listener": "SocialiteProviders\\Azure\\AzureExtendSocialite@handle",
  "socialite_name": "azure"
}, {
  "name": "Microsoft Live",
  "github": "https://github.com/SocialiteProviders/Microsoft-Live",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/microsoft-live",
  "listener": "SocialiteProviders\\Live\\LiveExtendSocialite@handle",
  "socialite_name": "live"
}, {
  "name": "Mixcloud",
  "github": "https://github.com/SocialiteProviders/Mixcloud",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/mixcloud",
  "listener": "SocialiteProviders\\Mixcloud\\MixcloudExtendSocialite@handle"
}, {
  "name": "Moves",
  "github": "https://github.com/SocialiteProviders/Moves",
  "maintainer": "bryceadams",
  "maintainer_profile": "https://github.com/bryceadams",
  "packagist": "socialiteproviders/moves",
  "listener": "SocialiteProviders\\Moves\\MovesExtendSocialite@handle"
}, {
  "name": "Naver",
  "github": "https://github.com/SocialiteProviders/Naver",
  "maintainer": "visualplus",
  "maintainer_profile": "https://github.com/visualplus",
  "packagist": "socialiteproviders/naver",
  "listener": "SocialiteProviders\\Naver\\NaverExtendSocialite@handle"
}, {
  "name": "Okta",
  "github": "https://github.com/SocialiteProviders/Okta",
  "maintainer": "chaseconey",
  "maintainer_profile": "https://github.com/chaseconey",
  "packagist": "socialiteproviders/okta",
  "listener": "SocialiteProviders\\Okta\\OktaExtendSocialite@handle",
  "extra_service_lines": [{
    "key": "BASE_URL",
    "value": "BASE_URL"
  }]
}, {
  "name": "Paymill",
  "github": "https://github.com/SocialiteProviders/Paymill",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/paymill",
  "listener": "SocialiteProviders\\Paymill\\PaymillExtendSocialite@handle"
}, {
  "name": "PayPal",
  "github": "https://github.com/SocialiteProviders/PayPal",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/paypal",
  "listener": "SocialiteProviders\\PayPal\\PayPalExtendSocialite@handle"
}, {
  "name": "PayPal Sandbox",
  "github": "https://github.com/SocialiteProviders/PayPal-Sandbox",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/paypal-sandbox",
  "listener": "SocialiteProviders\\PayPalSandbox\\PayPalSandboxExtendSocialite@handle",
  "socialite_name": "paypal_sandbox"
}, {
  "name": "Pinterest",
  "github": "https://github.com/SocialiteProviders/Pinterest",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/pinterest",
  "listener": "SocialiteProviders\\Pinterest\\PinterestExtendSocialite@handle"
}, {
  "name": "Podio",
  "github": "https://github.com/SocialiteProviders/Podio",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/podio",
  "listener": "SocialiteProviders\\Podio\\PodioExtendSocialite@handle"
}, {
  "name": "Pushbullet",
  "github": "https://github.com/SocialiteProviders/Pushbullet",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/pushbullet",
  "listener": "SocialiteProviders\\Pushbullet\\PushbulletExtendSocialite@handle"
}, {
  "name": "QQ",
  "github": "https://github.com/SocialiteProviders/QQ",
  "maintainer": "runphp",
  "maintainer_profile": "https://github.com/runphp",
  "packagist": "socialiteproviders/qq",
  "listener": "SocialiteProviders\\QQ\\QqExtendSocialite@handle"
}, {
  "name": "Rdio",
  "github": "https://github.com/SocialiteProviders/Rdio",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/rdio",
  "listener": "SocialiteProviders\\Rdio\\RdioExtendSocialite@handle"
}, {
  "name": "Readability",
  "github": "https://github.com/SocialiteProviders/Readability",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/readability",
  "listener": "SocialiteProviders\\Readability\\ReadabilityExtendSocialite@handle"
}, {
  "name": "Reddit",
  "github": "https://github.com/SocialiteProviders/Reddit",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/reddit",
  "listener": "SocialiteProviders\\Reddit\\RedditExtendSocialite@handle"
}, {
  "name": "RunKeeper",
  "github": "https://github.com/SocialiteProviders/RunKeeper",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/runkeeper",
  "listener": "SocialiteProviders\\RunKeeper\\RunKeeperExtendSocialite@handle"
}, {
  "name": "SalesForce",
  "github": "https://github.com/SocialiteProviders/SalesForce",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/salesforce",
  "listener": "SocialiteProviders\\SalesForce\\SalesForceExtendSocialite@handle"
}, {
  "name": "Slack",
  "github": "https://github.com/SocialiteProviders/Slack",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/slack",
  "listener": "SocialiteProviders\\Slack\\SlackExtendSocialite@handle"
}, {
  "name": "Smashcast",
  "github": "https://github.com/SocialiteProviders/Smashcast",
  "maintainer": "HutterValentin",
  "maintainer_profile": "https://github.com/valh1996",
  "packagist": "socialiteproviders/smashcast",
  "listener": "SocialiteProviders\\Smashcast\\SmashcastExtendSocialite@handle"
}, {
  "name": "SoundCloud",
  "github": "https://github.com/SocialiteProviders/SoundCloud",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/soundcloud",
  "listener": "SocialiteProviders\\SoundCloud\\SoundCloudExtendSocialite@handle"
}, {
  "name": "SharePoint",
  "github": "https://github.com/SocialiteProviders/SharePoint",
  "maintainer": "kaiten65",
  "maintainer_profile": "https://github.com/kaiten65",
  "packagist": "socialiteproviders/sharepoint",
  "listener": "SocialiteProviders\\SharePoint\\SharePointExtendSocialite@handle"
}, {
  "name": "Spotify",
  "github": "https://github.com/SocialiteProviders/Spotify",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/spotify",
  "listener": "SocialiteProviders\\Spotify\\SpotifyExtendSocialite@handle"
}, {
  "name": "StackExchange",
  "github": "https://github.com/SocialiteProviders/StackExchange",
  "maintainer": "AndyWendt",
  "maintainer_profile": "https://github.com/AndyWendt",
  "packagist": "socialiteproviders/stackexchange",
  "listener": "SocialiteProviders\\StackExchange\\StackExchangeExtendSocialite@handle",
  "extra_service_lines": [{
    "key": "key",
    "value": "KEY"
  }, {
    "key": "site",
    "value": "SITE"
  }]
}, {
  "name": "Steam",
  "github": "https://github.com/SocialiteProviders/Steam",
  "maintainer": "eklundchristopher",
  "maintainer_profile": "https://github.com/eklundchristopher",
  "packagist": "socialiteproviders/steam",
  "listener": "SocialiteProviders\\Steam\\SteamExtendSocialite@handle"
}, {
  "name": "StockTwits",
  "github": "https://github.com/SocialiteProviders/StockTwits",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/stocktwits",
  "listener": "SocialiteProviders\\StockTwits\\StockTwitsExtendSocialite@handle"
}, {
  "name": "Strava",
  "github": "https://github.com/SocialiteProviders/Strava",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/strava",
  "listener": "SocialiteProviders\\Strava\\StravaExtendSocialite@handle"
}, {
  "name": "Stripe",
  "github": "https://github.com/SocialiteProviders/Stripe",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/stripe",
  "listener": "SocialiteProviders\\Stripe\\StripeExtendSocialite@handle"
}, {
  "name": "Trello",
  "github": "https://github.com/SocialiteProviders/Trello",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/trello",
  "listener": "SocialiteProviders\\Trello\\TrelloExtendSocialite@handle"
}, {
  "name": "Tumblr",
  "github": "https://github.com/SocialiteProviders/Tumblr",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/tumblr",
  "listener": "SocialiteProviders\\Tumblr\\TumblrExtendSocialite@handle"
}, {
  "name": "Twitch",
  "github": "https://github.com/SocialiteProviders/Twitch",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/twitch",
  "listener": "SocialiteProviders\\Twitch\\TwitchExtendSocialite@handle"
}, {
  "name": "Twitter",
  "github": "https://github.com/SocialiteProviders/Twitter",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/twitter",
  "listener": "SocialiteProviders\\Twitter\\TwitterExtendSocialite@handle"
}, {
  "name": "Uber",
  "github": "https://github.com/SocialiteProviders/Uber",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/uber",
  "listener": "SocialiteProviders\\Uber\\UberExtendSocialite@handle"
}, {
  "name": "Venmo",
  "github": "https://github.com/SocialiteProviders/Venmo",
  "maintainer": "dabernathy89",
  "maintainer_profile": "https://github.com/dabernathy89",
  "packagist": "socialiteproviders/venmo",
  "listener": "SocialiteProviders\\Venmo\\VenmoExtendSocialite@handle"
}, {
  "name": "VersionOne",
  "github": "https://github.com/SocialiteProviders/VersionOne",
  "maintainer": "xdzeta",
  "maintainer_profile": "https://github.com/xdzeta",
  "packagist": "socialiteproviders/versionone",
  "listener": "SocialiteProviders\\VersionOne\\VersionOneExtendSocialite@handle"
}, {
  "name": "Vimeo",
  "github": "https://github.com/SocialiteProviders/Vimeo",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/vimeo",
  "listener": "SocialiteProviders\\Vimeo\\VimeoExtendSocialite@handle"
}, {
  "name": "VKontakte",
  "github": "https://github.com/SocialiteProviders/VKontakte",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/vkontakte",
  "listener": "SocialiteProviders\\VKontakte\\VKontakteExtendSocialite@handle"
}, {
  "name": "Weibo",
  "github": "https://github.com/SocialiteProviders/Weibo",
  "maintainer": "xyxu",
  "maintainer_profile": "https://github.com/xyxu",
  "packagist": "socialiteproviders/weibo",
  "listener": "SocialiteProviders\\Weibo\\WeiboExtendSocialite@handle"
}, {
  "name": "Weixin",
  "github": "https://github.com/SocialiteProviders/Weixin",
  "maintainer": "xyxu",
  "maintainer_profile": "https://github.com/xyxu",
  "packagist": "socialiteproviders/weixin",
  "listener": "SocialiteProviders\\Weixin\\WeixinExtendSocialite@handle"
}, {
  "name": "Weixin Web",
  "github": "https://github.com/SocialiteProviders/Weixin-Web",
  "maintainer": "xyxu",
  "maintainer_profile": "https://github.com/xyxu",
  "packagist": "socialiteproviders/weixin-web",
  "listener": "SocialiteProviders\\WeixinWeb\\WeixinWebExtendSocialite@handle",
  "socialite_name": "weixinweb"
}, {
  "name": "WordPress",
  "github": "https://github.com/SocialiteProviders/WordPress",
  "maintainer": "AndyWendt",
  "maintainer_profile": "https://github.com/AndyWendt",
  "packagist": "socialiteproviders/wordpress",
  "listener": "SocialiteProviders\\WordPress\\WordPressExtendSocialite@handle"
}, {
  "name": "Xing",
  "github": "https://github.com/SocialiteProviders/Xing",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/xing",
  "listener": "SocialiteProviders\\Xing\\XingExtendSocialite@handle"
}, {
  "name": "xREL",
  "github": "https://github.com/SocialiteProviders/xREL",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/xrel",
  "listener": "SocialiteProviders\\xREL\\xRELExtendSocialite@handle"
}, {
  "name": "Yahoo",
  "github": "https://github.com/SocialiteProviders/Yahoo",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/yahoo",
  "listener": "SocialiteProviders\\Yahoo\\YahooExtendSocialite@handle"
}, {
  "name": "Yammer",
  "github": "https://github.com/SocialiteProviders/Yammer",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/yammer",
  "listener": "SocialiteProviders\\Yammer\\YammerExtendSocialite@handle"
}, {
  "name": "Yandex",
  "github": "https://github.com/SocialiteProviders/Yandex",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/yandex",
  "listener": "SocialiteProviders\\Yandex\\YandexExtendSocialite@handle"
}, {
  "name": "YouTube",
  "github": "https://github.com/SocialiteProviders/YouTube",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/youtube",
  "listener": "SocialiteProviders\\YouTube\\YouTubeExtendSocialite@handle"
}, {
  "name": "Zendesk",
  "github": "https://github.com/SocialiteProviders/Zendesk",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/zendesk",
  "listener": "SocialiteProviders\\Zendesk\\ZendeskExtendSocialite@handle",
  "extra_service_lines": [{
    "key": "subdomain",
    "value": "subdomain"
  }]
}, {
  "name": "RedBooth",
  "github": "https://github.com/SocialiteProviders/Redbooth",
  "maintainer": "Ivar Smits",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/redbooth",
  "listener": "SocialiteProviders\\RedBooth\\RedBoothExtendSocialite@handle"
}, {
  "name": "Trakt",
  "github": "https://github.com/SocialiteProviders/Trakt",
  "maintainer": "Dimitris Zavantias",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/trakt",
  "listener": "SocialiteProviders\\Trakt\\TraktExtendSocialite@handle"
}, {
  "name": "Patreon",
  "github": "https://github.com/SocialiteProviders/Patreon",
  "maintainer": "Pieter Maes",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/patreon",
  "listener": "SocialiteProviders\\Patreon\\PatreonExtendSocialite@handle"
}, {
  "name": "Dataporten",
  "github": "https://github.com/SocialiteProviders/Dataporten",
  "maintainer": "Jørgen Birkhaug",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/dataporten",
  "listener": "SocialiteProviders\\Dataporten\\DataportenExtendSocialite@handle"
}, {
  "name": "Battle.net",
  "github": "https://github.com/SocialiteProviders/Battlenet",
  "maintainer": "faustbrian",
  "maintainer_profile": "https://github.com/faustbrian",
  "packagist": "socialiteproviders/battlenet",
  "listener": "SocialiteProviders\\Battlenet\\BattlenetExtendSocialite@handle"
}, {
  "name": "Shopify",
  "github": "https://github.com/SocialiteProviders/Shopify",
  "maintainer": "CullenIO",
  "maintainer_profile": "https://github.com/CullenIO",
  "packagist": "socialiteproviders/shopify",
  "listener": "SocialiteProviders\\Shopify\\ShopifyExtendSocialite@handle"
}, {
  "name": "Microsoft Graph",
  "github": "https://github.com/SocialiteProviders/Microsoft-Graph",
  "maintainer": "CJEdgerton",
  "maintainer_profile": "https://github.com/CJEdgerton",
  "packagist": "socialiteproviders/microsoft-graph",
  "listener": "SocialiteProviders\\Graph\\GraphExtendSocialite@handle",
  "socialite_name": "graph"
}, {
  "name": "Acclaim",
  "github": "https://github.com/SocialiteProviders/Acclaim",
  "maintainer": "pavankumarkatakam",
  "maintainer_profile": "https://github.com/pavankumarkatakam",
  "packagist": "socialiteproviders/acclaim",
  "listener": "SocialiteProviders\\Acclaim\\AcclaimExtendSocialite@handle"
}, {
  "name": "SciStarter",
  "github": "https://github.com/SocialiteProviders/SciStarter",
  "maintainer": "ryanvade",
  "maintainer_profile": "https://github.com/ryanvade",
  "packagist": "socialiteproviders/scistarter",
  "listener": "SocialiteProviders\\SciStarter\\SciStarterExtendSocialite@handle"
}, {
  "name": "Yiban",
  "github": "https://github.com/SocialiteProviders/Yiban",
  "maintainer": "orochizzzzzzz",
  "maintainer_profile": "https://github.com/orochizzzzzzz",
  "packagist": "socialiteproviders/yiban",
  "listener": "SocialiteProviders\\Yiban\\YibanExtendSocialite@handle"
}, {
  "name": "TVShowTime",
  "github": "https://github.com/SocialiteProviders/TVShowTime",
  "maintainer": "Henokv",
  "maintainer_profile": "https://github.com/Henokv",
  "packagist": "socialiteproviders/tvshowtime",
  "listener": "SocialiteProviders\\TVShowTime\\TVShowTimeExtendSocialite@handle"
}, {
  "name": "Unsplash",
  "github": "https://github.com/SocialiteProviders/Unsplash",
  "maintainer": "mayoz",
  "maintainer_profile": "https://github.com/mayoz",
  "packagist": "socialiteproviders/unsplash",
  "listener": "SocialiteProviders\\Unsplash\\UnsplashExtendSocialite@handle"
}, {
  "name": "ProjectV",
  "github": "https://github.com/SocialiteProviders/ProjectV",
  "maintainer": "vreezy",
  "maintainer_profile": "https://github.com/vreezy",
  "packagist": "socialiteproviders/projectv",
  "listener": "SocialiteProviders\\ProjectV\\ProjectVExtendSocialite@handle"
}, {
  "name": "QuickBooks",
  "github": "https://github.com/SocialiteProviders/QuickBooks",
  "maintainer": "alexhouse",
  "maintainer_profile": "https://github.com/alexhouse",
  "packagist": "socialiteproviders/quickbooks",
  "listener": "SocialiteProviders\\QuickBooks\\QuickBooksExtendSocialite@handle"
}, {
  "name": "Mixer",
  "github": "https://github.com/SocialiteProviders/Mixer",
  "maintainer": "hootener",
  "maintainer_profile": "https://github.com/hootener",
  "packagist": "socialiteproviders/mixer",
  "listener": "SocialiteProviders\\Mixer\\MixerExtendSocialite@handle"
}, {
  "name": "GameWisp",
  "github": "https://github.com/SocialiteProviders/GameWisp",
  "maintainer": "hootener",
  "maintainer_profile": "https://github.com/hootener",
  "packagist": "socialiteproviders/gamewisp",
  "listener": "SocialiteProviders\\GameWisp\\GameWispExtendSocialite@handle"
}, {
  "name": "HubSpot",
  "github": "https://github.com/SocialiteProviders/HubSpot",
  "maintainer": "swilla",
  "maintainer_profile": "https://github.com/swilla",
  "packagist": "socialiteproviders/hubspot",
  "listener": "SocialiteProviders\\HubSpot\\HubSpotExtendSocialite@handle"
}, {
  "name": "Untappd",
  "github": "https://github.com/SocialiteProviders/Untappd",
  "maintainer": "arsoba",
  "maintainer_profile": "https://github.com/arsoba",
  "packagist": "socialiteproviders/untappd",
  "listener": "SocialiteProviders\\Untappd\\UntappdExtendSocialite@handle"
}, {
  "name": "ArcGIS",
  "github": "https://github.com/SocialiteProviders/ArcGIS",
  "maintainer": "davidpiesse",
  "maintainer_profile": "https://github.com/davidpiesse",
  "packagist": "socialiteproviders/arcgis",
  "listener": "SocialiteProviders\\ArcGIS\\ArcGISExtendSocialite@handle"
}, {
  "name": "Ufutx",
  "github": "https://github.com/SocialiteProviders/Ufutx",
  "maintainer": "glore",
  "maintainer_profile": "https://github.com/glore",
  "packagist": "socialiteproviders/ufutx",
  "listener": "SocialiteProviders\\Ufutx\\UfutxExtendSocialite@handle"
}, {
  "name": "Discogs",
  "github": "https://github.com/SocialiteProviders/Discogs",
  "maintainer": "bbeng89",
  "maintainer_profile": "https://github.com/bbeng89",
  "packagist": "socialiteproviders/discogs",
  "listener": "SocialiteProviders\\Discogs\\DiscogsExtendSocialite@handle"
}]
